# A hopefully reproducible script
# Zihao He, 25/Mar/2021, zhe986@aucklanduni.ac.nz

## Assuming that this is on a clean installation of R Studio, and we want pretty graphs to come with the tables.
## As this is a R script, please run each step by "ctrl+enter" to ensure fewer errors as the program is being knit.
library(tidyverse) 
## make sure it is tidyverse, a common mistake is to put in tinyverse here. Experienced it before, got confused for half an hour at times as a result of this.
library(ggplot2)
library(dplyr)
## this makes R use the datasheet, please make sure that the csv file is in the same folder as this script to avoid having to additionally insert the entire file pathway, or just go to "import Dataset"
dicots <- read.csv ("dicots.csv")
## type in the whole path to the .csv file just in case
summary(dicots) 
## A little bit of statistics across all counts
## the datasheet in R automatically uses alphabetic order to suggest the control of the data, so the following is to show how to change this
dicots$Treatment <- factor (dicots$Treatment, ordered = FALSE)
## this tells R to undo the order of treatments, helps us with re-ordering it to have control be first
dicots_ctrl <- dicots %>% mutate (Treatment = relevel(dicots$Treatment, "Control"))
## This in essence is saying make the treatment control be first or default
summary(dicots_ctrl)
## when comparing in the console, we should see that control is above biocontrol this time
dicots_ctrl_lm <- lm(Total_natives ~ Treatment, data = dicots_ctrl)
## This is an ANOVA to see if the treatments will help with local dicot populations.
summary(dicots_ctrl_lm)
## The table generated by the above command will show 2 key bits of info, the T and P values which determines the treatments efficacy

## this will be a box plot without error bars
ggplot(data = dicots_ctrl, aes(x = Treatment, y = Total_natives)) +
  geom_boxplot() +
  ggtitle("Effects of Herbicides, Insecticides, beetles on native plantlife counts") +
  ylab("Total_natives") +
  xlab("Treatments") +
  theme_grey() 
  

